### ISSUE TITLE
Filter stack trace in reporting

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium#50]
*Platform* (JVM and/or JS): JVM/JS

## Code related feature
Most of the times, I am not interested in the full stack trace if a test fails. We could omit the stack trace all together but that would be too much, because:
- I want to see the stack trace if an unexpected exception occurred.
- If one defines more than one assertion per test (which is not recommended but I guess people do it) and depending on what kind of assertions one makes it might be handy to know on which line it failed. E.g. in the following I would only see; `assert: false to be true` but wouldn't know which one failed.
   ```
   assert(someComplexMethodAndIamNotAwareOfReturnValueOf()).toBe(true)
   assert(anotherMethod()).toBe(true)
   ```
- Having a file + line number in the output is handy since I am able to jump to the test within IntelliJ

Thus for the following
```
assert(1).toBe(2)
```
I would like to see something like the following:
```
assert: 1        (kotlin.Int <1165303897>)
◆ to be: 2        (kotlin.Int <887750041>)

at DummySpec$1$1.invoke(DummySpec.kt:14)
```

Yet, sometimes we might use own assertion functions and in such a case it is not enough to show the first stack frame which is not atrium specific. Therefore:
- filter out atrium specific frames
- filter out spek/junit specific frames (optional)

Currently it shows up in reporting (using Spek intelliJ Plugin) as follows:
```
assert: 1        (kotlin.Int <1165303897>)
◆ to be: 2        (kotlin.Int <887750041>)
java.lang.AssertionError: assert: 1        (kotlin.Int <1165303897>)
◆ to be: 2        (kotlin.Int <887750041>)
	at ch.tutteli.atrium.core.robstoll.lib.checking.ThrowingAssertionChecker.check(ThrowingAssertionChecker.kt:42)
	at ch.tutteli.atrium.creating.AssertionPlantWithCommonFields$CommonFields.check(AssertionPlantWithCommonFields.kt:71)
	at ch.tutteli.atrium.core.robstoll.lib.creating.MutableListBasedReportingAssertionPlant.checkAssertions(MutableListBasedReportingAssertionPlant.kt:21)
	at ch.tutteli.atrium.core.robstoll.lib.creating.MutableListBasedReportingAssertionPlant.addAssertion(MutableListBasedReportingAssertionPlant.kt:15)
	at ch.tutteli.atrium.api.cc.infix.en_GB.AnyAssertionsKt.toBe(anyAssertions.kt:19)
	at ThrowableStackTest$1$2.invoke(ThrowableStackTest.kt:18)
	at ThrowableStackTest$1$2.invoke(ThrowableStackTest.kt:8)
	at org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:102)
	at org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:80)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
```
In such a case I am not really interested in the stack trace. I know that I just run the test. The output should be reduced to
```` 
assert: 1        (kotlin.Int <1165303897>)
◆ to be: 2        (kotlin.Int <887750041>)

at ThrowableStackTest$1$2.invoke(ThrowableStackTest.kt:18)
at ThrowableStackTest$1$2.invoke(ThrowableStackTest.kt:8)
```` 

Running the same from gradle (also using Spek) results in:
```
Spek:DummySpec:it will fail on purpose
    => java.lang.AssertionError: assert: 1        (kotlin.Int <1986901753>)
◆ to be: 2        (kotlin.Int <1871689990>)
       ch.tutteli.atrium.core.robstoll.lib.checking.ThrowingAssertionChecker.check(ThrowingAssertionChecker.kt:
42)
       ch.tutteli.atrium.creating.AssertionPlantWithCommonFields$CommonFields.check(AssertionPlantWithCommonFie
lds.kt:71)
       ch.tutteli.atrium.core.robstoll.lib.creating.MutableListBasedReportingAssertionPlant.checkAssertions(Mut
ableListBasedReportingAssertionPlant.kt:21)
       ch.tutteli.atrium.core.robstoll.lib.creating.MutableListBasedReportingAssertionPlant.addAssertion(Mutabl
eListBasedReportingAssertionPlant.kt:15)
       ch.tutteli.atrium.api.cc.infix.en_GB.AnyAssertionsKt.toBe(anyAssertions.kt:19)
       DummySpec$1$2.invoke(DummySpec.kt:19)
       DummySpec$1$2.invoke(DummySpec.kt:9)
       org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:102)
       org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:80)
       org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.jav
a:105)
```
Also here, I don't need the stack since I have enough information from Spek (that depends on the used junit reporter I reckon but that's not Atrium's concern). 

Running the test using Mocha (JS Platform)
```
1) ch.tutteli.atrium.core.polyfills
       DummySpec
         itWillFailOnPurpose:
     assert: 1        (Int <1>)
◆ to be: 2        (Int <2>)
      at ThrowingAssertionChecker.check_i2wsmx$ (build\node_modules\atrium-core-robstoll-lib-js.js:148:25)
      at AssertionPlantWithCommonFields$CommonFields.check_tgi7xs$ (build\node_modules\atrium-core-api-js.js:13
47:27)
      at ReportingAssertionPlantImpl.MutableListBasedReportingAssertionPlant.checkAssertions_8qzvkp$_0 (build\n
ode_modules\atrium-core-robstoll-lib-js.js:277:25)
      at ReportingAssertionPlantImpl.MutableListBasedReportingAssertionPlant.addAssertion_94orq3$ (build\node_m
odules\atrium-core-robstoll-lib-js.js:272:10)
      at toBe (build\node_modules\atrium-api-cc-infix-en_GB-js.js:95:22)
      at DummySpec.itWillFailOnPurpose (build\classes\kotlin\test\atrium-core-api-js_test.js:308:5)
      at Context.<anonymous> (build\classes\kotlin\test\atrium-core-api-js_test.js:838:34)
```
Same, the stack trace is not necessary (depends on the chosen reporter).

**Comment by robstoll** [comment]
Atrium throws now an AtriumError (a subclass of AssertionError) and provides a AtriumErrorAdjuster which filters the stack as desired (currently with option, no-filtering, filter test runners and/or filter Atrium stack frames).
